[package]
name = "libdof"
version = "0.3.0"
edition = "2021"
authors = ["Oxey", "Asya"]
description = ".dof file protocol, a keyboard layout format specification"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/O-X-E-Y/libdof"
documentation = "https://docs.rs/libdof"


[dependencies]
serde = { version = "1.0.153", features = ["derive"] }
serde_json = "1.0.94"
serde_with = "2.2.0"
thiserror = "1.0.39"
