[package]
name = "libdof"
version = "0.6.0"
edition = "2021"
authors = ["Oxey", "Asya"]
description = ".dof file protocol, a keyboard layout format specification"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/O-X-E-Y/libdof"
documentation = "https://docs.rs/libdof"


[lib]
name = "libdof"
crate-type = ["cdylib"]


[dependencies]
pyo3 = { version = "0.19.2", optional = true }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_with = "3.3.0"
thiserror = "1.0.49"

[features]
pyo3 = ["dep:pyo3"]
